name: portifolio
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  animations_package:
    git: https://github.com/Luanftg/animations_package
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.9
  file_picker: ^8.0.0+1
  firebase_storage: ^11.6.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/projects/
    - assets/images/
    - assets/certificates/flutter/
    - assets/certificates/c#/
    - assets/db.json
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
    
    - family: Sixtyfour
      fonts:
        - asset: assets/fonts/Sixtyfour-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
